# Generated by Django 5.1.2 on 2024-10-30 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductosExtras',
            fields=[
                ('id_prod', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=15)),
                ('tipo', models.CharField(max_length=10)),
                ('talla', models.CharField(max_length=5)),
                ('peso', models.FloatField()),
                ('precio_uni', models.FloatField()),
                ('id_proveedor', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
