# Generated by Django 5.1.2 on 2024-10-30 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('Id_cliente', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('num_celular', models.IntegerField()),
                ('direccion', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=20)),
            ],
        ),
    ]
