# Generated by Django 5.1.2 on 2024-10-30 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id_venta', models.IntegerField(primary_key=True, serialize=False)),
                ('id_producto', models.IntegerField()),
                ('cliente', models.CharField(max_length=15)),
                ('cantidad', models.IntegerField()),
                ('precio', models.CharField(max_length=10)),
                ('gramos', models.FloatField()),
                ('servicios', models.CharField(max_length=15)),
                ('id_empleado', models.IntegerField()),
            ],
        ),
    ]
