# Generated by Django 5.1.2 on 2024-10-30 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_proveedor', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=60)),
                ('telefono', models.CharField(max_length=12)),
                ('c_electronico', models.CharField(max_length=25)),
                ('stock', models.CharField(max_length=10)),
                ('fecha_ult_entrega', models.DateField()),
            ],
        ),
    ]
