# Generated by Django 5.1.2 on 2024-10-30 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_proveedor', models.IntegerField(primary_key=True, serialize=False)),
                ('num_ruta', models.PositiveSmallIntegerField()),
                ('cant_prod', models.IntegerField()),
                ('peso', models.FloatField()),
                ('id_empleado', models.IntegerField()),
                ('tipo_prod', models.CharField(max_length=50)),
            ],
        ),
    ]
