# Generated by Django 5.1.2 on 2024-10-30 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id_empleado', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=15)),
                ('apellido', models.CharField(max_length=20)),
                ('rfc', models.CharField(max_length=12)),
                ('curp', models.CharField(max_length=12)),
                ('num_celular', models.IntegerField()),
                ('direccion', models.CharField(max_length=50)),
                ('sexo', models.CharField(max_length=10)),
            ],
        ),
    ]
