# Generated by Django 5.1.2 on 2024-10-30 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id_clientes', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=80)),
                ('telefono', models.CharField(max_length=12)),
            ],
        ),
    ]
